services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
      args:
        PHP_VERSION: ${PHP_VERSION:-8.3}
    container_name: laravel-app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  web:
    image: nginx:1.27-alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
